---
- hosts: webserver
  become: true
  tasks:
    - name: install pip
      package:
        name: python3-pip
        state: present

    - name: Run Docker
      raw: docker run -d --name webapp01 -p 8080:8080 milindtech/mtwebapp:4.0