---
- hosts: webserver
  become: true
  tasks:
    - name: install pip
      package:
        name: python3-pip
        state: present

    - name: install docker-py
      command:
        name: pip3 install docker-py

    - name: Restart a container
      docker_container:
        name: webapp01
        image: milindtech/mtwebapp:4.0
        state: started
        ports:
        - "8080:8080"
