---
- hosts: local
  tasks:
    - name: Create a new EC2 key
      ec2_key:
         name: webserver
         region: ap-south-1
      register: ec2_key_result

    - name: Save private key
      copy: content="{{ ec2_key_result.key.private_key }}" dest="/root/.ssh/webserver.pem" mode=0600
      when: ec2_key_result.changed
    - name: Provision EC2 instance
      ec2:
         key_name: webserver
         id: webserver
         region: ap-south-1
         instance_type: t2.micro
         image: ami-016ec067d44808c4f
         wait: yes
         count: 1
         instance_tags:
            Name: AWS-Ansible
         volumes:
            - device_name: /dev/xvda
              volume_type: gp2
              volume_size: 8
         vpc_subnet_id: subnet-696b2301
         assign_public_ip: yes
         group: Linux_Sg_Default_VPC
      register: ec2

    - name: Add the newly created EC2 instance(s) to the local host group
      local_action: lineinfile
                    path=hosts
                    insertafter='\[webserver\]' line='{{ item.private_ip }} ansible_ssh_user=centos ansible_ssh_private_key_file=/root/.ssh/webserver.pem ansible_ssh_common_args="-o StrictHostKeyChecking=no"'
      with_items: "{{ ec2.instances }}"